/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "PWM_1.h"
#include "Counter_1.h"
#include "color_sensor_s0_aliases.h"
#include "color_sensor_s0.h"
#include "color_sensor_s1_aliases.h"
#include "color_sensor_s1.h"
#include "color_sensor_s2_aliases.h"
#include "color_sensor_s2.h"
#include "color_sensor_s3_aliases.h"
#include "color_sensor_s3.h"
#include "color_sensor_led_aliases.h"
#include "color_sensor_led.h"
#include "color_sensor_out_aliases.h"
#include "color_sensor_out.h"
#include "Clock_1.h"
#include "isr_1.h"
#include "UART_1.h"
#include "Control_Reg_1.h"
#include "isr_2.h"
#include "UART_1_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

