/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "motor_l_pwm.h"
#include "motor_r_pwm.h"
#include "Clock_1.h"
#include "motor_l_in1_aliases.h"
#include "motor_l_in1.h"
#include "motor_l_in2_aliases.h"
#include "motor_l_in2.h"
#include "motor_r_in1_aliases.h"
#include "motor_r_in1.h"
#include "motor_r_in2_aliases.h"
#include "motor_r_in2.h"
#include "motor_l_quaddec.h"
#include "motor_l_quaddec_PVT.h"
#include "motor_l_phaseA_aliases.h"
#include "motor_l_phaseA.h"
#include "motor_l_phaseB_aliases.h"
#include "motor_l_phaseB.h"
#include "motor_r_phaseA_aliases.h"
#include "motor_r_phaseA.h"
#include "motor_r_quaddec.h"
#include "motor_r_quaddec_PVT.h"
#include "motor_r_phaseB_aliases.h"
#include "motor_r_phaseB.h"
#include "p_controller_isr.h"
#include "p_controller_timer.h"
#include "motor_l_quaddec_isr.h"
#include "motor_l_quaddec_Cnt16.h"
#include "motor_r_quaddec_isr.h"
#include "motor_r_quaddec_Cnt16.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

